### ISSUE TITLE
Use Bootstrap 4.x

### ISSUE THREAD

**Issue by aparcar** [mwarning/yet-another-firmware-selector#10]
This makes the website also usable via mobile devices

**Comment by mwarning** [comment]
It is probably easy to do even without bootstrap. Just say'in. :p

**Comment by aparcar** [comment]
I think LuCI as well as the OpenWrt websites moves to Bootstrap, so no time wasted in learning that :)

**Comment by aparcar** [comment]
![image](https://user-images.githubusercontent.com/16000931/74919531-d26ba780-536e-11ea-83f6-0e5c1e371a7b.png)

I worked a bit on it but maybe it is to much overhead. @mwarning if your up please integrate the new textarea/button in your current css and we skip bootstrap...

**Comment by mwarning** [comment]
I will give it a try.

**Comment by aparcar** [comment]
We still have to make it mobile friendly...

**Comment by mwarning** [comment]
It makes sense to use bootstrap if the design gets more complicated.
But I think that we should limit the project to basic and easy to implement features.

More complex scenarios are better served with a different project / fork of YAFS..
